name: Process Images with Real-ESRGAN

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有其他依赖，可以在这里安装
        # pip install some_dependency

        
    - name: Run text processing
      run: |
        cd realesrgan
        realesrgan-ncnn-vulkan.exe

 

    - name: Run image processing script
      run: |
        python 1.py

    - name: Archive output folder
      run: |
        tar -czf output.tar.gz output

    - name: Upload output archive
      uses: actions/upload-artifact@v2
      with:
        name: output-archive
        path: output.tar.gz
