name: Run Real-ESRGAN

on: [push, pull_request]

jobs:
  run-realesrgan:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        pip install -r requirements.txt

    - name: Download test image
      run: |
        curl -L -o input.png https://example.com/path/to/your/input.png

    - name: Run Real-ESRGAN
      run: |
        python inference_realesrgan.py -n RealESRGAN_x4plus -i input.png -o output --outscale 3.5 --face_enhance > output.log 2> error.log
      continue-on-error: true

    - name: Print logs
      run: |
        echo "Printing error log:"
        type error.log
        echo "Printing output log:"
        type output.log
      shell: pwsh

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          output.log
          error.log

    - name: Upload output image
      uses: actions/upload-artifact@v2
      with:
        name: output-image
        path: output
